version: "3.1"

services:
  backend:
    image: backend
    build:
      context: ./backend/
    ports:
      - "8080:8080"

  frontend:
    image: frontend
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend
