export const ADD_ITEM_BEGIN = "ADD_ITEM_BEGIN";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE";

export const GET_ITEMS_BEGIN = "GET_ITEMS_BEGIN";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE";

export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_BEGIN = "REGISTER_BEGIN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const RESET_REGISTER_INFO = "RESET_REGISTER_INFO";

export const GET_RESERVATIONS_BEGIN = "GET_RESERVATIONS_BEGIN";
export const GET_RESERVATIONS_SUCCESS = "GET_RESERVATIONS_SUCCESS";
export const GET_RESERVATIONS_FAILURE = "GET_RESERVATIONS_FAILURE";

export const GET_OFFERS_BEGIN = "GET_OFFERS_BEGIN";
export const GET_OFFERS_SUCCESS = "GET_OFFERS_SUCCESS";
export const GET_OFFERS_FAILURE = "GET_OFFERS_FAILURE";

export const GET_USER_LENDS_BEGIN = "GET_USER_LENDS_BEGIN";
export const GET_USER_LENDS_SUCCESS = "GET_USER_LENDS_SUCCESS";
export const GET_USER_LENDS_FAILURE = "GET_USER_LENDS_FAILURE";

export const GET_USER_BORROWS_BEGIN = "GET_USER_BORROWS_BEGIN";
export const GET_USER_BORROWS_SUCCESS = "GET_USER_BORROWS_SUCCESS";
export const GET_USER_BORROWS_FAILURE = "GET_USER_BORROWS_FAILURE";

export const ADD_ADDRESS_BEGIN = "ADD_ADDRESS_BEGIN";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAILURE = "ADD_ADDRESS_FAILURE";

export const GET_BOOKING_BEGIN = "GET_BOOKING_BEGIN";
export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";
export const GET_BOOKING_FAILURE = "GET_BOOKING_FAILURE";

export const GET_CATEGORIES_BEGIN = "GET_CATEGORIES_BEGIN";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const GET_CHAT_BEGIN = "GET_CHAT_BEGIN";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAILURE = "GET_CHAT_FAILURE";
