export const SET_PHOTO = "SET_PHOTO";

export const SET_NAME = "SET_NAME";
export const SET_DESCRIPTION = "SET_DESCRIPTION";
export const SET_PRICE = "SET_PRICE";
export const SET_CATEGORIES = "SET_CATEGORIES";

export const SET_START_DATE = "SET_START_DATE";
export const SET_END_DATE = "SET_END_DATE";

export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const SET_SHOW_MODAL = "SET_SHOW_MODAL";

export const CHANGE_FILTER = "CHANGE_FILTER";

export const SET_USERNAME = "SET_USERNAME";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_FIRSTNAME = "SET_FIRSTNAME";
export const SET_LASTNAME = "SET_LASTNAME";
export const SET_EMAIL = "SET_EMAIL";
export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER";
export const RESET_REGISTER_INPUTS = "RESET_REGISTER_INPUTS";

export const SET_USER_ADDRESS = "SET_USER_ADDRESS";

export const SET_CURRENT_THREAD = "SET_CURRENT_THREAD";
export const SET_MESSAGE = "SET_MESSAGE";

export const LOGOUT = "LOGOUT";

export const SET_CATEGORY_FILTER = "SET_CATEGORY_FILTER";
export const SET_MIN_PRICE_FILTER = "SET_MIN_PRICE_FILTER";
export const SET_MAX_PRICE_FILTER = "SET_MAX_PRICE_FILTER";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";

export const SET_IS_CENTERED = "SET_IS_CENTERED";
export const SET_CURRENT_CENTER = "SET_CURRENT_CENTER";
export const SET_USER_LOCATION = "SET_USER_LOCATION";
export const SET_USER_LOCATION_ALLOWED = "SET_USER_LOCATION_ALLOWED";
export const SET_HOME_TITLE = "SET_HOME_TITLE";
export const SET_LOCATION_TITLE = "SET_LOCATION_TITLE";
export const SET_HOVER_ITEM = "SET_HOVER_ITEM";
